<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql" Version="13.1.2" />
    <PackageReference Include="Aspire.StackExchange.Redis.OutputCaching" Version="13.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.13.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SportMap.AL.Abstractions\SportMap.AL.Abstractions.csproj" />
    <ProjectReference Include="..\SportMap.AL\SportMap.AL.csproj" />
    <ProjectReference Include="..\SportMap.ServiceDefaults\SportMap.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
